#
# Copyright (C) 2023 RyuujiX <saputradenny712@gmail.com>
# Copyright (C) 2023-2024 Kneba <abenkenary3@gmail.com>
#

name: Compile kernel

env:
   TOKEN: ${{ secrets.TOKEN }}
   USERNAME: ${{ secrets.USERNAME }}
   TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
   TG_TOKEN: ${{ secrets.TG_TOKEN }}

on: [push]

jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
    - uses: actions/checkout@v4
    - name: Setup CI
      run: |
         apt update -y && apt upgrade -y && apt install -y sudo
         sudo apt install glibc-source bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev openssl python-is-python3 wget zip zstd make gcc-arm-linux-gnueabi software-properties-common build-essential libarchive-tools gcc-aarch64-linux-gnu tzdata -y || exit 1
         sudo rm -rf /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
    - name: Setup and Build Kernel
      run: bash build.sh

    - uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.TG_CHAT_ID }} # user id or channel name secret
        token: ${{ secrets.TG_TOKEN }} # token secret
        status: ${{ job.status }} # do not modify this line
