#
# Copyright (C) 2023-2024 Kneba <abenkenary3@gmail.com>
#

name: Compile kernel

env:
   TOKEN: ${{ secrets.TOKEN }}
   USERNAME: ${{ secrets.USERNAME }}
   TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
   TG_TOKEN: ${{ secrets.TG_TOKEN }}

on: [push]

jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: wizardprjkt/build:kernel
    steps:
    - uses: actions/checkout@v4
    - name: Setup and Build Kernel
      run: |
        git clone --depth=1 --recursive https://$USERNAME:$TOKEN@github.com/Tiktodz/android_kernel_asus_sdm636 -b tom/eol/hmp kernel && cd kernel
        bash build.sh
